name: Deploy TrackMyGym to AWS EC2

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd ICTNE24_Semesterarbeit3_L.M
          git pull origin main
          
          # Stop all services
          docker-compose down
          
          # Clean up old containers and images
          docker system prune -f
          
          # Build new images (PostgreSQL needs fresh build)
          docker-compose build --no-cache
          
          # Start services with PostgreSQL health checks
          docker-compose up -d
          
          # Wait for PostgreSQL to be ready
          echo "Waiting for PostgreSQL to be ready..."
          sleep 30
          
          # Check if all services are healthy
          docker-compose ps
          
          # Test database connection
          docker-compose exec -T postgres pg_isready -U trackmygym_user -d trackmygym || echo "PostgreSQL not ready yet"
          
          # Optional: Test health endpoints
          sleep 10
          curl -f http://localhost/api/health || echo "Health check failed"