name: PR Health Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create test environment file
      run: |
        echo "DB_PASSWORD=test_password_123" > .env
        echo "SECRET_KEY=test_secret_key" >> .env
    
    - name: Build Docker images
      run: |
        docker-compose build --no-cache
    
    - name: Test containers start
      run: |
        # Start all services
        docker-compose up -d
        
        # Wait for PostgreSQL to be ready
        echo "Waiting for services to start..."
        sleep 45
        
        # Check container status
        docker-compose ps
        
        # Test PostgreSQL connection
        docker-compose exec -T postgres pg_isready -U trackmygym_user -d trackmygym
        
        # Test service health endpoints
        docker-compose exec -T user-service curl -f http://localhost:5001/health || echo "User service health check failed"
        docker-compose exec -T workout-service curl -f http://localhost:5002/health || echo "Workout service health check failed"
        docker-compose exec -T stats-service curl -f http://localhost:5003/health || echo "Stats service health check failed"
        
        # Check logs for errors
        docker-compose logs --tail=50
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v
        docker system prune -f