
name: PR Health Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        docker-compose build
    
    - name: Test containers start
      run: |
        docker-compose up -d
        sleep 30
        docker-compose ps
        docker-compose down
